services:
  wedding-api:
    build: ../api
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    environment:
      - DB_HOST=db
  db:
    image: postgres:18.2
    environment:
      POSTGRES_DB: "wedding"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/wedding -schemas=public -user=postgres -password=postgres migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../schema/sql:/flyway/sql

volumes:
  db_data:
    driver: local
