services:
  db:
    image: postgres:18.2
    environment:
      POSTGRES_DB: "wedding"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/wedding -schemas=public -user=postgres -password=postgres migrate
    depends_on:
      - db
    volumes:
      - ../schema/sql:/flyway/sql

volumes:
  db_data:
    driver: local
